# Generated by Django 4.1.6 on 2023-02-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='Images/None/sampleImage.jpg', upload_to='Images'),
        ),
    ]
